### ISSUE TITLE
Original Sources

### ISSUE THREAD

**Issue by SergeyIlyin** [sshunsuke/glfMB#1]
Can you share the original sources (1985, 1989)?

**Comment by sshunsuke** [comment]
Sorry. I cannot do this. The copyrights of them belong to publishers. However, you might be able to read Brill & Mukherjee (1999) on a web site below. 
https://www.academia.edu/16612028/Multiphase_Flow_In_Wells_J_P_Brill_and_Mukherjee

The model used in the code is explained in Page 44-46 (Chapter 4) in the book.
